apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: P4ssw0rd
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: P4ssw0rd
        - name: MYSQL_DATABASE
          value: contactos
        volumeMounts:
        - name: mysql-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-script
        configMap:
          name: init.sql
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
