apiVersion: v1
data:
  DB_NAME: Y29udGFjdG9z
  DB_PASSWORD: UDRzc3cwcmQ=
  DB_USER: dXNlcg==
  HOST: bXlzcWwuZGVmYXVsdC5zdmM=
kind: Secret
metadata:
  name: credenciales
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front
  name: front
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: front
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: credenciales
        image: juanconde24/front-nodejs-mysql
        imagePullPolicy: Always
        name: node-mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
